### PR TITLE
Updated Dependencies in README

### PR DESCRIPTION
**Pull request by ishansaraf**
No code changes, just updated the README.md to have the torrent client dependency as mentioned in an issue.

### CODE REVIEW

**Comment by professorjamesmoriarty** [comment]
I'd put this under optional depends. Or a side note in general. As it's not required to run, but part of its use for sure.

**Comment by ishansaraf** [comment]
Yeah, but looking at the Katastrophe file, it seems like it wouldn't work unless one of those 2 clients are installed (for Windows atleast), so can't use any torrent client - at least for now.

**Comment by professorjamesmoriarty** [comment]
@ishansaraf indeed, but to that end listing a depends makes little sense for other platforms. You're idea isnt wrong, just needs a bit a tweaking to mention the need for a client on linux for example that can open magnet links etc (deluge ftw lol).

Maybe a `Requires:` section? With a list of possible clients for each platform?

**Comment by ishansaraf** [comment]
@shaggytwodope Yeah good point, let me make a few edits.

**Pull request merged**
